language: php
php:
  - 5.5
  - 5.4

env:
  global:
  - secure: "l9eM9SX0z2MbRKGLSXljcMH/HDbcKxf+qEFg+gcwIEB9HhaotPigmlG+xkax+NFytB55CK8u4ZL17/axpqtTMiVhKF34CeRmAAQJg8TwwqGS53XBbpEe/vDeqzQWJ60P2PM5t1sghBSSN06kLtZP41NI4q5tRyN0ZBe2S0xDeFY="




before_script:
  ##install doxygen
  - sudo apt-get install doxygen
  ## doxygen : output folder
  - mkdir -p doc

script:
  ## We actualy do the tests
  - "phpunit --configuration phpunit.xml"
  ## We generate the documentation
  - doxygen

after_script:
 ## PHPDocumentor : Upload vers les GitHub Pages
 - bash .travis_shell_after_success.sh

